# SPDX-FileCopyrightText: 2022-2023 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
    tags:
      - 'v*'

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/ci.yml@dfc77e139ee278bd4e7acdd92b03d037c0998919 # v1.0.3
    secrets: inherit
